name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Static checks
        run: |
          python -m compileall codex_addons
          python3 -m codex_addons.list_sessions --plain --limit 1 || true
